#!/usr/bin/env python2
'''
@author: Thomas
'''
import logging, sys
import os.path

def main():
    logging.basicConfig(level=logging.WARN, stream=sys.stdout, format="%(levelname)s:%(name)s:%(funcName)s:%(message)s") 
    import e3_io
    config = e3_io.ConfigManager().get_config()
    #sys.path.append(config['eulerXPath'])
    
    lastArg = sys.argv[-1]
    if lastArg.startswith("--e3Dir="):
        if os.path.isdir(lastArg.split("=")[1]):
            e3_io.e3Dir = lastArg.split("=")[1]
        sys.argv = sys.argv[0:-1]
    
    run = None
    import e3_run
    import e3_parse
    if len(sys.argv) > 1:
        run = e3_run.OneShot(e3_parse.CommandProvider())
    else:
        run = e3_run.Interactive(e3_parse.CommandProvider())
    run.run()
    
if __name__ == '__main__':
    #import networkx as nx
    #import numpy as np
    #import matplotlib.pyplot as plt
    
    #G = nx.Graph()
    #G.add_edges_from(
    #    [('A', 'B'), ('A', 'C'), ('D', 'B'), ('E', 'C'), ('E', 'F'),
    #     ('B', 'H'), ('B', 'G'), ('B', 'F'), ('C', 'G')])
    #nx.draw(G, cmap = plt.get_cmap('jet'),)
    #plt.show()
    
    
    main()
