#!/usr/bin/env python
'''
@author: Thomas
'''
import logging, sys
import e3_run
import e3_parse
import e3_io

def main():
    logging.basicConfig(level=logging.INFO, stream=sys.stdout, format="%(levelname)s:%(name)s:%(funcName)s:%(message)s")
    config = e3_io.get_config()
    #sys.path.append(config['eulerXPath'])
    
    run = None
    if len(sys.argv) > 1:
        run = e3_run.OneShot(e3_parse.CommandProvider())
    else:
        run = e3_run.Interactive(e3_parse.CommandProvider())
    run.run()
    
if __name__ == '__main__':
    #import networkx as nx
    #import numpy as np
    #import matplotlib.pyplot as plt
    
    #G = nx.Graph()
    #G.add_edges_from(
    #    [('A', 'B'), ('A', 'C'), ('D', 'B'), ('E', 'C'), ('E', 'F'),
    #     ('B', 'H'), ('B', 'G'), ('B', 'F'), ('C', 'G')])
    #nx.draw(G, cmap = plt.get_cmap('jet'),)
    #plt.show()
    
    main()